In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.metrics import mean_squared_error

In [2]:
df_red = pd.read_csv("C:/AI_study/winequality-red.csv", sep=';')
df_red

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0               7.4             0.700         0.00             1.9      0.076   
1               7.8             0.880         0.00             2.6      0.098   
2               7.8             0.760         0.04             2.3      0.092   
3              11.2             0.280         0.56             1.9      0.075   
4               7.4             0.700         0.00             1.9      0.076   
...             ...               ...          ...             ...        ...   
1594            6.2             0.600         0.08             2.0      0.090   
1595            5.9             0.550         0.10             2.2      0.062   
1596            6.3             0.510         0.13             2.3      0.076   
1597            5.9             0.645         0.12             2.0      0.075   
1598            6.0             0.310         0.47             3.6      0.067   

      free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
0                    11.0                  34.0  0.99780  3.51       0.56   
1                    25.0                  67.0  0.99680  3.20       0.68   
2                    15.0                  54.0  0.99700  3.26       0.65   
3                    17.0                  60.0  0.99800  3.16       0.58   
4                    11.0                  34.0  0.99780  3.51       0.56   
...                   ...                   ...      ...   ...        ...   
1594                 32.0                  44.0  0.99490  3.45       0.58   
1595                 39.0                  51.0  0.99512  3.52       0.76   
1596                 29.0                  40.0  0.99574  3.42       0.75   
1597                 32.0                  44.0  0.99547  3.57       0.71   
1598                 18.0                  42.0  0.99549  3.39       0.66   

      alcohol  quality  
0         9.4        5  
1         9.8        5  
2         9.8        5  
3         9.8        6  
4         9.4        5  
...       ...      ...  
1594     10.5        5  
1595     11.2        6  
1596     11.0        6  
1597     10.2        5  
1598     11.0        6  

[1599 rows x 12 columns]

In [3]:
df_white = pd.read_csv("C:/AI_study/winequality-white.csv",sep=';')
df_white

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0               7.0              0.27         0.36            20.7      0.045   
1               6.3              0.30         0.34             1.6      0.049   
2               8.1              0.28         0.40             6.9      0.050   
3               7.2              0.23         0.32             8.5      0.058   
4               7.2              0.23         0.32             8.5      0.058   
...             ...               ...          ...             ...        ...   
4893            6.2              0.21         0.29             1.6      0.039   
4894            6.6              0.32         0.36             8.0      0.047   
4895            6.5              0.24         0.19             1.2      0.041   
4896            5.5              0.29         0.30             1.1      0.022   
4897            6.0              0.21         0.38             0.8      0.020   

      free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
0                    45.0                 170.0  1.00100  3.00       0.45   
1                    14.0                 132.0  0.99400  3.30       0.49   
2                    30.0                  97.0  0.99510  3.26       0.44   
3                    47.0                 186.0  0.99560  3.19       0.40   
4                    47.0                 186.0  0.99560  3.19       0.40   
...                   ...                   ...      ...   ...        ...   
4893                 24.0                  92.0  0.99114  3.27       0.50   
4894                 57.0                 168.0  0.99490  3.15       0.46   
4895                 30.0                 111.0  0.99254  2.99       0.46   
4896                 20.0                 110.0  0.98869  3.34       0.38   
4897                 22.0                  98.0  0.98941  3.26       0.32   

      alcohol  quality  
0         8.8        6  
1         9.5        6  
2        10.1        6  
3         9.9        6  
4         9.9        6  
...       ...      ...  
4893     11.2        6  
4894      9.6        5  
4895      9.4        6  
4896     12.8        7  
4897     11.8        6  

[4898 rows x 12 columns]

In [4]:
df = pd.concat([df_red, df_white], axis=0)
df

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0               7.4              0.70         0.00             1.9      0.076   
1               7.8              0.88         0.00             2.6      0.098   
2               7.8              0.76         0.04             2.3      0.092   
3              11.2              0.28         0.56             1.9      0.075   
4               7.4              0.70         0.00             1.9      0.076   
...             ...               ...          ...             ...        ...   
4893            6.2              0.21         0.29             1.6      0.039   
4894            6.6              0.32         0.36             8.0      0.047   
4895            6.5              0.24         0.19             1.2      0.041   
4896            5.5              0.29         0.30             1.1      0.022   
4897            6.0              0.21         0.38             0.8      0.020   

      free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
0                    11.0                  34.0  0.99780  3.51       0.56   
1                    25.0                  67.0  0.99680  3.20       0.68   
2                    15.0                  54.0  0.99700  3.26       0.65   
3                    17.0                  60.0  0.99800  3.16       0.58   
4                    11.0                  34.0  0.99780  3.51       0.56   
...                   ...                   ...      ...   ...        ...   
4893                 24.0                  92.0  0.99114  3.27       0.50   
4894                 57.0                 168.0  0.99490  3.15       0.46   
4895                 30.0                 111.0  0.99254  2.99       0.46   
4896                 20.0                 110.0  0.98869  3.34       0.38   
4897                 22.0                  98.0  0.98941  3.26       0.32   

      alcohol  quality  
0         9.4        5  
1         9.8        5  
2         9.8        5  
3         9.8        6  
4         9.4        5  
...       ...      ...  
4893     11.2        6  
4894      9.6        5  
4895      9.4        6  
4896     12.8        7  
4897     11.8        6  

[6497 rows x 12 columns]

In [5]:
y = df['residual sugar']
y

0       1.9
1       2.6
2       2.3
3       1.9
4       1.9
       ... 
4893    1.6
4894    8.0
4895    1.2
4896    1.1
4897    0.8
Name: residual sugar, Length: 6497, dtype: float64

In [6]:
x= df.drop('residual sugar',axis=1)
x

fixed acidity  volatile acidity  citric acid  chlorides  \
0               7.4              0.70         0.00      0.076   
1               7.8              0.88         0.00      0.098   
2               7.8              0.76         0.04      0.092   
3              11.2              0.28         0.56      0.075   
4               7.4              0.70         0.00      0.076   
...             ...               ...          ...        ...   
4893            6.2              0.21         0.29      0.039   
4894            6.6              0.32         0.36      0.047   
4895            6.5              0.24         0.19      0.041   
4896            5.5              0.29         0.30      0.022   
4897            6.0              0.21         0.38      0.020   

      free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
0                    11.0                  34.0  0.99780  3.51       0.56   
1                    25.0                  67.0  0.99680  3.20       0.68   
2                    15.0                  54.0  0.99700  3.26       0.65   
3                    17.0                  60.0  0.99800  3.16       0.58   
4                    11.0                  34.0  0.99780  3.51       0.56   
...                   ...                   ...      ...   ...        ...   
4893                 24.0                  92.0  0.99114  3.27       0.50   
4894                 57.0                 168.0  0.99490  3.15       0.46   
4895                 30.0                 111.0  0.99254  2.99       0.46   
4896                 20.0                 110.0  0.98869  3.34       0.38   
4897                 22.0                  98.0  0.98941  3.26       0.32   

      alcohol  quality  
0         9.4        5  
1         9.8        5  
2         9.8        5  
3         9.8        6  
4         9.4        5  
...       ...      ...  
4893     11.2        6  
4894      9.6        5  
4895      9.4        6  
4896     12.8        7  
4897     11.8        6  

[6497 rows x 11 columns]

In [7]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=423)

In [8]:
from sklearn.svm import SVR

clf_svm = SVR()
clf_svm.fit(X_train, y_train)

pred_svm = clf_svm.predict(X_test)

print("\n--- SVM Regressor ---")
print(pred_svm)
print(clf_svm.score(X_train, y_train))


--- SVM Regressor ---
[4.68988091 2.0535131  3.42561669 ... 2.2188462  2.11926011 7.74578528]
0.2422659196224104


In [9]:
mse = np.sqrt(mean_squared_error(pred_svm, y_test))
print('평균제곱근오차', mse)

평균제곱근오차 4.047089167839799


In [10]:
from sklearn.linear_model import LinearRegression

clf_lr = LinearRegression()
clf_lr.fit(X_train, y_train)

pred_lr = clf_lr.predict(X_test)

print ("\n--- Logistic Regression Regressor ---")
print(pred_lr)
print(clf_lr.score(X_train, y_train))


--- Logistic Regression Regressor ---
[ 3.23579004 10.86853834  5.5612205  ...  3.01542694  1.7495476
  4.26859716]
0.8618964516985015


In [11]:
mse = np.sqrt(mean_squared_error(pred_lr, y_test))
print('평균제곱근오차', mse)

평균제곱근오차 1.701991930908737


In [12]:
from sklearn.metrics import mean_squared_error
from sklearn.metrics import confusion_matrix

from sklearn.tree import DecisionTreeRegressor

clf_dt = DecisionTreeRegressor()
clf_dt.fit(X_train, y_train)

pred_dt = clf_dt.predict(X_test)

print ("\n--- Decision Tree Regressor ---")
print(pred_dt)
print(clf_dt.score(X_train, y_train))


--- Decision Tree Regressor ---
[ 1.7 15.2  1.8 ...  2.   2.1  1.8]
0.9999965090086905


In [13]:
mse = np.sqrt(mean_squared_error(pred_dt, y_test))
print('평균제곱근오차', mse)

평균제곱근오차 1.8036869291707855


In [14]:
from sklearn.ensemble import RandomForestRegressor

rf_clf = RandomForestRegressor()
rf_clf.fit(X_train, y_train)

pred_rf = rf_clf.predict(X_test)

print ("\n--- Random Forest Regressor ---")
print(pred_rf)
print(rf_clf.score(X_train, y_train))


--- Random Forest Regressor ---
[ 2.1645 12.357   3.9075 ...  2.1665  1.991   2.9165]
0.9883170403877505


In [15]:
mse = np.sqrt(mean_squared_error(pred_rf, y_test))
print('평균제곱근오차', mse)

평균제곱근오차 1.1971164317973604


In [16]:
from sklearn.neighbors import KNeighborsRegressor

# KNN 회귀 모델 생성
clf_knn = KNeighborsRegressor()
clf_knn.fit(X_train, y_train)

# 테스트 데이터에 대한 예측
pred_knn = clf_knn.predict(X_test)

# 훈련 데이터에 대한 모델의 성능 출력 (R-squared)
print ("\n--- KNeighbors Classifier ---")
print(pred_knn)
print(clf_knn.score(X_train, y_train))


--- KNeighbors Classifier ---
[ 4.2   6.86  1.24 ...  2.14  2.48 11.48]
0.5571727144530392


In [17]:
mse = np.sqrt(mean_squared_error(pred_knn, y_test))
print('평균제곱근오차', mse)

평균제곱근오차 3.9398539703512245


In [18]:
# 결측치 확인
df.isnull().sum()

fixed acidity           0
volatile acidity        0
citric acid             0
residual sugar          0
chlorides               0
free sulfur dioxide     0
total sulfur dioxide    0
density                 0
pH                      0
sulphates               0
alcohol                 0
quality                 0
dtype: int64

In [19]:
# polynomialFeateures 적용
from sklearn.preprocessing import PolynomialFeatures

poly = PolynomialFeatures(include_bias=False)

poly.fit(X_train)
train_poly = poly.transform(X_train)
print(train_poly.shape)

(5197, 77)


In [20]:
poly.get_feature_names_out()

array(['fixed acidity', 'volatile acidity', 'citric acid', 'chlorides',
       'free sulfur dioxide', 'total sulfur dioxide', 'density', 'pH',
       'sulphates', 'alcohol', 'quality', 'fixed acidity^2',
       'fixed acidity volatile acidity', 'fixed acidity citric acid',
       'fixed acidity chlorides', 'fixed acidity free sulfur dioxide',
       'fixed acidity total sulfur dioxide', 'fixed acidity density',
       'fixed acidity pH', 'fixed acidity sulphates',
       'fixed acidity alcohol', 'fixed acidity quality',
       'volatile acidity^2', 'volatile acidity citric acid',
       'volatile acidity chlorides',
       'volatile acidity free sulfur dioxide',
       'volatile acidity total sulfur dioxide',
       'volatile acidity density', 'volatile acidity pH',
       'volatile acidity sulphates', 'volatile acidity alcohol',
       'volatile acidity quality', 'citric acid^2',
       'citric acid chlorides', 'citric acid free sulfur dioxide',
       'citric acid total sulfur dioxid

In [21]:
test_poly = poly.transform(X_test)

In [22]:
# LinearRegression을 통해 score 비교
# polynomialFeatures 적용 전 score 0.8618964516985015

from sklearn.linear_model import LinearRegression

clf_lr = LinearRegression()
clf_lr.fit(train_poly, y_train)

pred_lr = clf_lr.predict(test_poly)

print ("\n--- Logistic Regression Regressor ---")
print(pred_lr)
print(clf_lr.score(train_poly, y_train))


--- Logistic Regression Regressor ---
[ 3.46574445 10.98706186  5.61175574 ...  2.97096602  1.50226427
  1.07351103]
0.9200098431126986


In [23]:
mse = np.sqrt(mean_squared_error(pred_rf, y_test))
print('평균제곱근오차', mse)

평균제곱근오차 1.1971164317973604


In [24]:
# 표준화 StandardScaler 
from sklearn.preprocessing import StandardScaler

ss = StandardScaler()
ss.fit(train_poly)
train_scaled = ss.transform(train_poly)
test_scaled = ss.transform(test_poly)

In [25]:
# LinearRegression을 통해 score 비교
# polynomialFeatures 적용 전 score 0.9200098431126986

from sklearn.linear_model import LinearRegression

clf_lr = LinearRegression()
clf_lr.fit(train_scaled, y_train)

pred_lr = clf_lr.predict(test_scaled)

print ("\n--- Logistic Regression Regressor ---")
print(pred_lr)
print(clf_lr.score(train_scaled, y_train))


--- Logistic Regression Regressor ---
[ 3.46574445 10.98706186  5.61175574 ...  2.97096602  1.50226428
  1.07351103]
0.9200098431127042


In [26]:
mse = np.sqrt(mean_squared_error(pred_rf, y_test))
print('평균제곱근오차', mse)

평균제곱근오차 1.1971164317973604


In [27]:
# 표준화 MinMaxScaler
from sklearn.preprocessing import MinMaxScaler

mm = MinMaxScaler()
mm.fit(train_poly)
train_scaled = mm.transform(train_poly)
test_scaled = mm.transform(test_poly)

In [28]:
# LinearRegression을 통해 score 비교

from sklearn.linear_model import LinearRegression

clf_lr = LinearRegression()
clf_lr.fit(train_scaled, y_train)

pred_lr = clf_lr.predict(test_scaled)

print ("\n--- Logistic Regression Regressor ---")
print(pred_lr)
print(clf_lr.score(train_scaled, y_train))


--- Logistic Regression Regressor ---
[ 3.46574445 10.98706186  5.61175574 ...  2.97096602  1.50226428
  1.07351103]
0.9200098431127062


In [29]:
mse = np.sqrt(mean_squared_error(pred_rf, y_test))
print('평균제곱근오차', mse)

평균제곱근오차 1.1971164317973604


In [30]:
# 표준화 RobustScaler
from sklearn.preprocessing import RobustScaler

rs = RobustScaler()
rs.fit(train_poly)
train_scaled = rs.transform(train_poly)
test_scaled = rs.transform(test_poly)

In [31]:
# LinearRegression을 통해 score 비교

from sklearn.linear_model import LinearRegression

clf_lr = LinearRegression()
clf_lr.fit(train_scaled, y_train)

pred_lr = clf_lr.predict(test_scaled)

print ("\n--- Logistic Regression Regressor ---")
print(pred_lr)
print(clf_lr.score(train_scaled, y_train))


--- Logistic Regression Regressor ---
[ 3.46574445 10.98706186  5.61175574 ...  2.97096602  1.50226428
  1.07351103]
0.9200098431127045


In [32]:
mse = np.sqrt(mean_squared_error(pred_rf, y_test))
print('평균제곱근오차', mse)

평균제곱근오차 1.1971164317973604
